#! /bin/bash

# This is a PAM module, to be called from `pam_exec.so`.
# This module checks if the loggin user has too many open SSH
# connections, if yes, then stop the loggin.
#
# Example
# 
# session required pam_exec.so stdout /home/qiqig/shine-cluster/login/checkConnections 5
#
# The maximum SSH connections is 5.

limit=$1
c=$(pgrep -xcu $PAM_USER sshd)
if (( c >= limit / 2 )); then
	echo "Max $limit ssh connections are allowed, and you already have $c. Reboot your machine to clear useless connections."

	if (( c >= limit )); then
		exit 1
	fi
fi
