#! /usr/bin/zsh -e

setopt extended_glob
# --force bypasses the error
# "rm: missing operand", when there are no files to delete.
rm --force /dev/rNvidia[0-9]#(N)
nvidias=( $(printf '%s\n' /dev/nvidia[0-9]# | shuf) )

for ((i = 1; i <= $#nvidias; i++)) do
	echo "Link "${nvidias[$i]}" to rNvidia$((i-1))"
	ln -s ${nvidias[$i]} /dev/rNvidia$((i-1))
done
