#!/bin/bash -e

tips=(
"Besides ""copy that"", you can say ""roger that"". ""Roger wilco"" means in addition to ""roger that"", you WILl COmply. These are radio communication jardons. 

In United States, ""Say again"", from the same category, is much more often used than ""Pardon"".
--Qiqi"

"Did you say Beech Tree or Peachtree? Was that Mr. Gota or Mr. Goda? Steven or Stephen? Pirate Way or Pilot Way?
中国人英语发音不标准，打电话时名字、电话号码、email更是说不清。你可以用北约音标字符。
Q as Queue, I as India, Q as Queue, I as India, G as Golf, U as Uniform. 数字0有特殊念法。
If you use NATO code adeptly, people may think you are a respected veteran!
--Qiqi"

"In Vim, press gg in normal mode to go to the beginning of the file, press $(tput bold)G$(tput sgr0) to go to the end. Press $(tput bold)^$(tput sgr0) to the beginning of the line, $(tput bold)&$(tput sgr0) to the end of the line.
Press $(tput bold)w$(tput sgr0) to go to the next Word, $(tput bold)b$(tput sgr0) goes Backwords."

"阿基米德被皇帝要求检查皇冠是不是纯金的。阿基米德泡澡时突然想到了浮体原理，不禁高兴的从浴盆跳了出来，赤身裸体跑了出去，边跑还边喊著：“eureka, eureka!”
eureka是希腊语，意思是$(tput setab 2)我发现了！$(tput setab 0)
In Civilization VI, you will also see eureka, which was implemented as a technology boost that fast-forwards your technology research progress from 0 to 50%.
--Qiqi"

"
$(tput smso)Tatooine is the name of a planet in Star Wars$(tput rmso)			$(tput setaf 11)x  x$(tput setaf 7)
$(tput smso)the young Skywalker Anakin's home.$(tput rmso)		$(tput setaf 11)o  o         x        x  $(tput setaf 7)
$(tput smso)The most famous view on Tatooine$(tput rmso)	     $(tput setaf 11)o        o     x          x $(tput setaf 7)
$(tput smso)is it's double sunset.$(tput rmso)			    $(tput setaf 11)o          o    x          x $(tput setaf 7)
					    $(tput setaf 11)o          o     x        x  $(tput setaf 7)
_______________________________________________________________________________
--Qiqi"

)
