#!/bin/bash

s=$(tput smul)
e=$(tput rmul)

tips=(
"These ${s}bright young things${e} have just started college.

young, enthusiastic, fashionable, or ambitious people"

"My assistant is a bit ${s}wet behind the ears${e}. He still has a lot to learn.

young and inexperienced"

"I've just turned 40, and I'm in ${s}the prime of my life${e}. I always go to the gym after work.

at my best; healthy and successful period or state"

"Katie started learning piano when she was ${s}knee-high to a grasshopper${e}.

very young, very short

grasshopper 蚱蜢"

"Derek and Joan spent their ${s}twilight years${e} traveling the world.

[C] the last years of someone's life"

"My grandpa got married again at the ${s}ripe old age${e} of 92.

very old age

ripe 成熟的"

"Sally first sang on stage at the ${s}tender age${e} of 7.

[sing.] very young age

tender 嫩的"

"Damien's at that ${s}awkward age${e} and finds it hard to talk to people.

the time of life when one is no longer a child and yet not properly grown up"

"Many singer's voices ${s}improve with age${e}.

get better as they got older"

"Harper regrets ${s}losing touch with${e} all her old school friends.

no longer being in contact with"

"I think Claire's found ${s}a soulmate${e}. Both she and Don love reading.

A person who shares a deep understanding or bond with another"

"I've ${s}kept in touch with${e} Lin since we left college 25 years ago.

continue to be in contact with"

"Marie and Pierre met through Isaac, ${s}a mutual friend${e} of theirs.

a shared friend of two people

mutual 相互的"

"Ramon and Tara ${s}get on like a house on fire${e}. They're always talking and laughing.

quickly get along extremely well; have a very good relationship"

"Mia and I have ${s}drifted apart${e} since she left our choir and started boxing instead.

gradually to lose mutual affection

choir合唱团"

"I ${s}struck up${e} a friendship with Pete while we were in a cooking class last year.

to start a relationship or conversation with someone

struck是strike的过去分词"

"My wife and I ${s}hit it off${e} immediately when we first met at a country music concert.

become friends very quickly"

"Donna was ${s}a fair-weather friend${e}. She wouldn't help when my house flooded.

somebody who stops being a friend when you are in trouble"

"Cy and I ${s}got off on the wrong foot${e} on our date. He was an hour late and forgot my name.

in a task or relationship, to start unsuccessfully."

"Bob reminds me so much of his father. He is ${s}a chip off the old block${e}.

a person who is very similar to their mother or father in the way that they look or behave"

"Uncle Tony is ${s}the black sheep of the family${e}. He's been to prison three times.

 A disreputable member of a family"

"We're ${s}bringing up${e} our children to be kind to animals.

teaching a child how to behave"

"We're ${s}a close-knit family${e}. We always meet up for birthdays and holidays.

a family in which everyone supports each other.

knit：v. (knit, knit)（使）紧密"

"Curly hair ${s}runs in our family${e}, and my daughter, mom, and I all have it.

is a common feature in our family"

"Leo ${s}bears a striking resemblance${e} to his grandfather.

looks extremely similar"

"Mateo and his brother Lucas are ${s}like two peas in a pod${e}. I can't tell them apart.

extremely similar to each other; indistinguishable."

"Karen is ${s}the spitting image of${e} that actor in the new sci-fi film.

to look exactly like somebody else

sci-fi: science fiction"

"You must eat something. You're ${s}all skin and bones${e}.

too thin"

"Oscar is only 25, but he's already ${s}getting thin on top${e}.

have no hair on top of the head"

"Rita ${s}looked like she'd seen a ghost${e} after I told her my news.

looks very scared or shocked"

"Rachel ${s}looked like a drowned rat${e} after she got caught in the rain on her way home.

was very wet

drowned淹死的"

"My aunt believed in ${s}keeping up appearances${e} despite having little money.

pretending that things are going well

keep sth <-> up：保持高水平"

"Domenica ${s}looked the part${e} for her first day of work at the bank.

to have an appearance befitting a particular character, role, or function."

"George arrived at the restaurant ${s}immaculately groomed${e} for his date with Cassie.

 perfectly clean or neat"

"Nalini ${s}never has a hair out of place${e}. She cares a lot about her appearance.

is extremely neat and well groomed.

well groomed 整洁且衣着得体"

"Philip ${s}was born with a silver spoon in his month${e}. He grew up in a castle in France.

was born into a wealthy family"

"Maxine is such ${s}a highflier${e}. She's been promoted twice this year and is only 23.

a very talented and successful person.

promote v. 提拔, 晋升"

"Danika's parents don't approve of Bob because he's from ${s}the wrong side of the tracks${e}.

the wrong social background or inferior part of town

approve of：不同意、不喜欢"

"My parents ${s}didn't have two pennies to rub together${e}, but we still had lots of fun.

were very poor

penny：英国的便士，0.1元
dime：美国的0.1元
cent：美国的0.01元"

"Lucia has ${s}a vivid imagination${e}. Her artworks are so original.

an ability to think of exciting images and ideas

vivid: （想象力）丰富的"

"Norah is such ${s}a fuddy-duddy${e}. She never wants to come out with us on Saturday night.

someone who is unwilling to try new things. An old-fashioned person"

"Gustav has ${s}a selfish streak${e}. He won't share his cookies with his friends.

streak: a part of a person's character, especially an unpleasant part"

"Arturo is so ${s}two-faced${e}. He said he liked my haircut but told his friends he hated it.

saying different things to different people about a particular subject"

"My dad's just an ${s}average Joe${e}. He enjoys burgers and fries, and loves watching baseball.

a stereotypical man who has simple tastes

stereotypical：符合刻板印象的"

"It was great to see Jasmine at the party. She's always ${s}a barrel of laughs${e}.

a fun person or situation

barrel：圆桶"

"Bob is such ${s}a crybaby${e}. He was very upset about not getting a perfect score.

someone who cries too often or without good reason"

"Zoe loves proving how much she knows. She's ${s}too smart for her own good${e}.

annoyingly proud of her intelligence or knowledge 太陈独秀了"

"Noah is really ${s}down to earth${e}. He earns lots of money, but he lives in a little cottage.

practical and unpretentious 接地气

unpretentious：不爱炫耀的"

"I know Rex looks a bit scary, but he ${s}wouldn't hurt a fly${e}.

is completely harmless

scary：吓人的
fly：苍蝇"

"Claire is ${s}a social butterfly${e}. She's always going to parties.

a very sociable person 交际花"

"My uncle's ${s}a lone wolf${e}. He lives on his own in a cabin in the forest.

someone who prefers to live or work alone

lone adj. 单独的，独自的"

"Tony ${s}wouldn't say boo to a goose${e}. He gets really shy when he talks to customers.

is very timid and nervous

timid：胆怯的"

"I do ${s}not know boo${e} about raising chickens.

know nothing about a topic. Frequently with 'about'."

"Jim's ${s}a good egg${e}. He helped me to move last week.

an honest, reliable, or considerate person"

"Hassan is ${s}the salt of the earth${e}. I saw him help an old lady cross the road.

kind, honest, and unpretentious 活雷锋

unpretentious：不张扬的"

"Debbie's ${s}a tough cookie${e}. She doesn't mind when people criticize her work.

determined and physically or emotionally strong

tough：嚼不烂的，剽悍的"

"Kirsty remained ${s}as cool as cucumber${e} throughout her performance.

very calm and showing control, especially in a difficult situation"

"My kids think this TV show is ${s}the best thing since sliced bread${e}.

extremely good, interesting"

"The ice cream at Giuseppe's parlor really is ${s}the bee's knees${e}!

an excellent person or thing

parlor：只卖一种东西的店
knee：膝盖"

"My new TV is ${s}miles ahead of${e} my old one.

much more advanced than"

"The view from the top of the mountain is totally ${s}out of this world${e}. You can see for miles.

used to emphasize how good, beautiful"

"We had a wonderful boat trip. ${s}The frosting on the cake${e} was seeing dolphins.

the best part of a good experience

frosting：糖霜，撒上去的东西"

"Losing my office job was ${s}a blessing in disguise${e}. My new job is much more interesting.

something that seems bad, but is actually good

in disguise：伪装了的"

"Chan's store only sells watches that are ${s}top of the line${e}.

the best quality"

"The burgers in Max's diner are ${s}to die for${e}. And they're huge!

就算死了也要（拿到、吃到）"

"Abel is a ${s}top-notch${e} reporter. He's interviewed some really famous actors.

highest quality

notch：等级"

"Karolina's cake is ${s}second to none${e}. It looks beautiful, and it tastes delicious.

far better than any others"

"Pete's habit of dropping litter ${s}leaves a bad taste in my mouth${e}.

makes me feel very uncomfortable

dropping litter: 乱扔垃圾"

"The weather in Hawaii ${s}didn't live up to expectations${e}. It rained every day.

was not as good as expected

expectation: 期望"

"Country music is ${s}not my cup of tea${e}. I prefer rock music.

not something I enjoy"

"Noah's old car is ${s}past its prime${e}. He's been driving it for years.

in a bad condition, or too old

cf. the prime of my life"

"The museum in my town is ${s}nothing to write home about${e}. There are very few exhibits.

not every impressive; ordinary"

"Watching golf on TV is so boring. It's ${s}like watching paint dry${e}.

extremely boring"

"His voice is OK, but he's ${s}not going to set the world on fire${e}.

not going to be very exciting or successful

set sth on fire：把东西点燃"

"It's still ${s}rough around the edges${e}, but this is my design for the park.

not perfect, unpolished, in need of more work"

"Rita's TV is ${s}on its last legs${e}. She's had it for over 10 years.

likely to stop functioning very soon"

"We had been really looking forward to the meal, but thought the food was ${s}a let-down${e}.

a disappointment"

"My old desktop computer is ${s}past its sell-by date${e}. It takes a long time to start up.

in need of replacing

sell-by date: 销售日期，保质期"

"Clarita's new apartment is tiny. There's ${s}not enough room to swing a cat${e}.

very little space

swing：摇摆"

"My colleagues all have terrible colds. They're ${s}dropping like fries${e}!

becoming sick, fall down or stop doing something, in large numbers"

"You're ${s}barking up the wrong tree${e} if you think I can help you with your homework.
I'm terrible at science.

#wasting effort by following the wrong course of action
to have the wrong idea about how to get or achieve something

bark：狗叫"

"The half-mile run was ${s}a two-horse race${e} between Beatriz and Maria.

a competition with only two clear possible winners"

"I ${s}chickened out of${e} diving off the top board in the pool. It was too high.

was too scared to"

"I told my boss I won't finish my report today, but she still keeps ${s}badgering me${e} about it.

repeatedly telling me to do something

badger：不断催促"

"It really ${s}gets my goat${e} when someone eats smelly food on the train.

irritates me

smelly: 有臭味的
irritate：使恼火"

"You can do anything now that you've finished college. ${s}The world is your oyster${e}.

You have lots of opportunities

oyster：生蚝"

"Frank ate ${s}the lion's share${e} of the cake. There wasn't enough for us.

the largest part"

"This little pill is supposed to help you lose 20 pounds? Yeah, ${s}in a pig's ear${e} it does.

猪才相信

也可作 in a pig's eye, in a pig's arse（屁股）"

"I don't like my job, but it ${s}puts food on the table${e}.

to earn enough money to live on"

"Sharon always ${s}spoon-feeds${e} her staff. She tells them exactly what to do.

gives too much help to

spoon: 勺子"

"Don't get so upset about burning the cookies. It's no use ${s}crying over spilled milk${e}.

getting upset about something that has already happened

spilled：洒出来的"

"Jennifer is such ${s}a couch potato${e}. She never goes out and watches TV all weekend instead.

a lazy person who watches too much TV

couch: 长沙发，长椅"

"I don't know whether to apply for this job. It looks really interesting but ${s}it pays peanuts${e}.

the salary is very low"

"Asher is such ${s}a butterfingers${e}. He is always dropping things.

a clumsy person who often drops things

clumsy：笨拙的"

"I'm really stressed! I think I ${s}bit off more than I could chew${e} when I took this promotion.

to try to do too much, or something that is too difficult

bit：咬 chew：嚼"

"I wanted Jo to water my plants when I was on vacation, 
so I ${s}buttered her up${e} by saying her backyard looked nice.

praised or flattered her so she would do me a favor

flatter：奉承"

"Copies of Sadie's new novel are ${s}selling like hotcakes${e} after it got great reviews.

selling quickly in large numbers

hotcake: 烤饼, 畅销品"

"You want to ${s}walk on eggshells${e} around Dylan. He gets upset so easily.

be very careful not to cause offense"

"My granddaughter is ${s}the apple of my eye${e}. I'm so proud of her.

a person I am very fond or proud of

fond：喜爱"

"Fiona told me she doesn't like my new scooter. I think it's just ${s}sour grapes${e}.

a jealous and bitter attitude

scooter：小型摩托车，滑板车
sour：酸的
jealous: 嫉妒的"
)

unset s
unset e

#echo "${#a[@]}"
