#!/bin/bash -e

export TERM=xterm-256color

out=/tmp/daily-tips
if [[ -s $out ]]; then
	cat /tmp/daily-tips
	lastrun=$(stat -c %Y "$out") || lastrun=0
	# 86400s is 24 hours.
	expiration=$(expr $lastrun + 86400)
	if [ $(date +%s) -lt $expiration ]; then
		exit
	fi
fi

exec > $out

# Allow * matches nothing so that groups is an empty array.
shopt -s nullglob
groups=(/etc/daily-tips/*)

i=$(($RANDOM % ${#groups[@]}))

filename=${groups[$i]}
source "$filename"

i=$(($RANDOM % ${#tips[@]}))

echo ""

var=${tips[$i]}
# remove leading whitespace characters
var="${var#"${var%%[![:space:]]*}"}"
# remove trailing whitespace characters
var="${var%"${var##*[![:space:]]}"}"


attribution=$(grep -P '(?<=--).+$' -o  <<< "${var##*$'\n'}" || true)
if [[ -z "$attribution" ]]; then
	echo "$var"
	echo -e "\t\t\t\t\tfrom $(basename "$filename")"
else
	echo "${var%$'\n'*}"
	echo -e "\t\t\t\t\tfrom $attribution, $(basename "$filename")"
fi

