#!/usr/bin/zsh

export TERM=xterm-256color

echo
if [[ -e /etc/diskquota/enable ]]; then
	echo -n "磁盘配额已启用。"
else
	percent=$(df --output=pcent /home | grep -o -P '\d+')
	if (( percent >= 45 )); then
		echo -n "目前/home目录已经${percent}%满。如果达到50%，将会启动磁盘配额。"
	else
		exit
	fi
fi

echo -n "配额上限被计算为$(tput smso)$(diskquota limit -h)$(tput rmso)。"

# https://superuser.com/a/1178598/150076
PPID1=`cat /proc/$PPID/status | grep PPid | awk '{ print $2 }'`
PPID2=`cat /proc/$PPID1/status | grep PPid | awk '{ print $2 }'`
USERNAME=`ps -x | grep $PPID2 | awk '{ print $6 }' |  sed "s/[[:digit:].-]//g"`
#uid=$(id -u $USERNAME)
exp=$(diskquota exempt check $USERNAME)
if [[ -n $exp ]]; then
	echo "你的存储豁免于${exp}过期。"
else
	echo "你有机会要求配额豁免。"
fi
echo "请参考 $(tput smul)https://github.com/gqqnbig/mpi-servers/issues/38$(tput rmul)"
